name: islamic_daily_routine_kids
description: A simplified Flutter app for kids to track daily prayers and learn Quran (Juz Amma) with child-friendly interface.
publish_to: 'none'
version: 1.8.2+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  
  # Prayer Times Calculation
  adhan: ^2.0.0+1
  
  # Location Services
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  
  # Local Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # Date/Time Utilities
  intl: ^0.20.2
  http: ^1.2.2
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # UUID generation
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  
  # Assets
  assets:
    - assets/images/
    - assets/sounds/
  
  # Add custom fonts if needed
  # fonts:
  #   - family: Arabic
  #     fonts:
  #       - asset: assets/fonts/Arabic.ttf

flutter_launcher_icons:
  android: true
  image_path: assets/images/app_logo.png
  min_sdk_android: 21
