// File generated by FlutterFire CLI.
// This is a placeholder file. You need to configure Firebase for your project.
// Follow the instructions in FIREBASE_SETUP.md to generate this file properly.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'This app only supports Android platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvE1rDVeB63m3CuYXJ9gJwo0miEIftlws',
    appId: '1:1083743231743:android:88c0a2fd16c227bec4b6ca',
    messagingSenderId: '1083743231743',
    projectId: 'daily-muslim-routine-kids',
    databaseURL: 'https://daily-muslim-routine-kids-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'daily-muslim-routine-kids.firebasestorage.app',
  );

}